---
apiVersion: gloo.solo.io/v1
kind: UpstreamGroup
metadata:
  name: upstreamgroup-blue
  namespace: appmesh-demo
spec:
  destinations:
  - destination:
      upstream:
        name: appmesh-demo-colorteller-blue-9080
        namespace: gloo-system
    weight: 80
  - destination:
      upstream:
        name: appmesh-demo-colorteller-bluesteel-9080
        namespace: gloo-system
    weight: 20
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: colorgateway
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matcher:
        prefix: /appmesh/blue
      routeAction:
        upstreamGroup:
          name: upstreamgroup-blue
          namespace: appmesh-demo
      routePlugins:
        prefixRewrite:
          prefixRewrite: /
    - matcher:
        prefix: /appmesh/color
      routeAction:
        single:
          upstream:
            name: appmesh-demo-colorgateway-9080
            namespace: gloo-system
      routePlugins:
        prefixRewrite:
          prefixRewrite: /color
