#bluesteel virtualnode
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-bluesteel
  namespace: appmesh-demo
spec:
  meshName: color-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: colorteller-bluesteel.appmesh-demo.svc.cluster.local
---
#bluesteel service
apiVersion: v1
kind: Service
metadata:
  name: colorteller-bluesteel
  namespace: appmesh-demo
  labels:
    app: colorteller
    version: bluesteel
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: colorteller
    version: bluesteel
#bluesteel deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller-bluesteel
  namespace: appmesh-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorteller
      version: bluesteel
  template:
    metadata:
      labels:
        app: colorteller
        version: bluesteel
    spec:
      containers:
        - name: colorteller
          image: 970805265562.dkr.ecr.us-west-2.amazonaws.com/colorteller:latest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 9080
          env:
            - name: "SERVER_PORT"
              value: "9080"
            - name: "COLOR"
              value: "bluesteel"

# vim: set ft=yaml:
