apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: GlooDemo
  region: us-east-2
  version: "1.13"

nodeGroups:
  - name: ng1-GlooDemo
    instanceType: m5.large
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        autoScaler: true
        #allow access AWS app mesh
        appMesh: true
        #allow access to AWS X-Ray
        xRay: true
        #allow access to AWS CloudWatch
        cloudWatch: true