apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: canary-colorteller-blue
  namespace: appmesh-demo
spec:
  provider: gloo
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: colorteller-blue
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: hpa-blue
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # container port
    port: 9080
  canaryAnalysis:
    # schedule interval (default 60s)
    interval: 10s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # Gloo Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      threshold: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      threshold: 500
      interval: 30s
    # # load testing (optional)
    # webhooks:
    #   - name: load-test
    # 
    #      url: http://flagger-loadtester.appmesh-demo/
    #     timeout: 5s
    #     metadata:
    #       type: cmd
    #       cmd: "hey -z 1m -q 10 -c 2 http://app.example.com/"
