
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-blue
  namespace: appmesh-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: colorteller-blue
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (100m)
      targetAverageUtilization: 99